spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}  
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mysell
    username: postgres
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/mysell
    user: postgres
    password: ${DB_PASSWORD}
    locations: classpath:db/migration

  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${SECRET}
