import { ProductSelect } from '../components/available-products/available-products.component';

export const AVAIABLE_PRODUCTS: ProductSelect[] = [
  {
    product: {
      id: '1',
      name: 'Arroz',
      category: 'Alimentos/Bebidas',
      purchasePrice: 5.5,
      sellingPrice: 7.0,
      brand: 'Tio João',
      measure: { quantity: 1, unitOfMeasure: 'kg' },
    },
    selected: false,
  },
  {
    product: {
      id: '2',
      name: 'Feijão',
      category: 'Alimentos/Bebidas',
      purchasePrice: 6.0,
      sellingPrice: 8.5,
      brand: 'Camil',
      measure: { quantity: 1, unitOfMeasure: 'kg' },
    },
    selected: false,
  },
  {
    product: {
      id: '3',
      name: 'Leite Integral',
      category: 'Alimentos/Bebidas',
      purchasePrice: 3.8,
      sellingPrice: 4.5,
      brand: 'Italac',
      measure: { quantity: 1, unitOfMeasure: 'litro' },
    },
    selected: false,
  },
  {
    product: {
      id: '4',
      name: 'Macarrão Espaguete',
      category: 'Alimentos/Bebidas',
      purchasePrice: 2.5,
      sellingPrice: 3.2,
      brand: 'Renata',
      measure: { quantity: 500, unitOfMeasure: 'g' },
    },
    selected: false,
  },
  {
    product: {
      id: '5',
      name: 'Farinha de Trigo',
      category: 'Alimentos/Bebidas',
      purchasePrice: 3.0,
      sellingPrice: 4.2,
      brand: 'Sol',
      measure: { quantity: 1, unitOfMeasure: 'kg' },
    },
    selected: false,
  },
  {
    product: {
      id: '6',
      name: 'Açúcar Cristal',
      category: 'Alimentos/Bebidas',
      purchasePrice: 4.0,
      sellingPrice: 5.5,
      brand: 'União',
      measure: { quantity: 1, unitOfMeasure: 'kg' },
    },
    selected: false,
  },
  {
    product: {
      id: '7',
      name: 'Café Torrado e Moído',
      category: 'Alimentos/Bebidas',
      purchasePrice: 8.0,
      sellingPrice: 10.0,
      brand: 'Pilão',
      measure: { quantity: 500, unitOfMeasure: 'g' },
    },
    selected: false,
  },
  {
    product: {
      id: '8',
      name: 'Óleo de Soja',
      category: 'Alimentos/Bebidas',
      purchasePrice: 4.5,
      sellingPrice: 6.0,
      brand: 'Liza',
      measure: { quantity: 900, unitOfMeasure: 'ml' },
    },
    selected: false,
  },
  {
    product: {
      id: '9',
      name: 'Sal Refinado',
      category: 'Alimentos/Bebidas',
      purchasePrice: 1.5,
      sellingPrice: 2.2,
      brand: 'Cisne',
      measure: { quantity: 1, unitOfMeasure: 'kg' },
    },
    selected: false,
  },
  {
    product: {
      id: '10',
      name: 'Pão de Forma',
      category: 'Alimentos/Bebidas',
      purchasePrice: 6.5,
      sellingPrice: 8.0,
      brand: 'Pullman',
      measure: { quantity: 500, unitOfMeasure: 'g' },
    },
    selected: false,
  },
  {
    product: {
      id: '11',
      name: 'Refrigerante Guaraná',
      category: 'Alimentos/Bebidas',
      purchasePrice: 4.0,
      sellingPrice: 6.0,
      brand: 'Antarctica',
      measure: { quantity: 2, unitOfMeasure: 'L' },
    },
    selected: false,
  },
  {
    product: {
      id: '12',
      name: 'Iogurte Natural',
      category: 'Alimentos/Bebidas',
      purchasePrice: 2.8,
      sellingPrice: 3.5,
      brand: 'Danone',
      measure: { quantity: 170, unitOfMeasure: 'g' },
    },
    selected: false,
  },
  {
    product: {
      id: '13',
      name: 'Carne Bovina',
      category: 'Alimentos/Bebidas',
      purchasePrice: 25.0,
      sellingPrice: 30.0,
      brand: 'Friboi',
      measure: { quantity: 1, unitOfMeasure: 'kg' },
    },
    selected: false,
  },
  {
    product: {
      id: '14',
      name: 'Frango Resfriado',
      category: 'Alimentos/Bebidas',
      purchasePrice: 8.0,
      sellingPrice: 10.0,
      brand: 'Sadia',
      measure: { quantity: 1, unitOfMeasure: 'kg' },
    },
    selected: false,
  },
  {
    product: {
      id: '15',
      name: 'Achocolatado em Pó',
      category: 'Alimentos/Bebidas',
      purchasePrice: 9.0,
      sellingPrice: 11.0,
      brand: 'Toddy',
      measure: { quantity: 400, unitOfMeasure: 'g' },
    },
    selected: false,
  },
  {
    product: {
      id: '16',
      name: 'Molho de Tomate',
      category: 'Alimentos/Bebidas',
      purchasePrice: 2.5,
      sellingPrice: 4.0,
      brand: 'Elefante',
      measure: { quantity: 340, unitOfMeasure: 'g' },
    },
    selected: false,
  },
  {
    product: {
      id: '17',
      name: 'Sabão em Pó',
      category: 'Produtos de Limpeza / Higiene',
      purchasePrice: 12.0,
      sellingPrice: 15.0,
      brand: 'Omo',
      measure: { quantity: 1, unitOfMeasure: 'kg' },
    },
    selected: false,
  },
  {
    product: {
      id: '18',
      name: 'Papel Higiênico',
      category: 'Beleza / Cuidados Pessoais / Higiene',
      purchasePrice: 10.0,
      sellingPrice: 13.0,
      brand: 'Neve',
      measure: { quantity: 4, unitOfMeasure: 'rolos' },
    },
    selected: false,
  },
  {
    product: {
      id: '19',
      name: 'Margarina',
      category: 'Alimentos/Bebidas',
      purchasePrice: 6.0,
      sellingPrice: 8.0,
      brand: 'Qualy',
      measure: { quantity: 500, unitOfMeasure: 'g' },
    },
    selected: false,
  },
  {
    product: {
      id: '20',
      name: 'Água Mineral',
      category: 'Alimentos/Bebidas',
      purchasePrice: 1.2,
      sellingPrice: 2.0,
      brand: 'Crystal',
      measure: { quantity: 500, unitOfMeasure: 'ml' },
    },
    selected: false,
  },
];
