INSERT INTO categories (name) VALUES
	('OTHERS'),
    ('Alimentos/Bebidas'),
    ('Tabaco/Cânabis'),
    ('Beleza / Cuidados Pessoais / Higiene'),
    ('Produtos de Limpeza / Higiene'),
    ('Calçados'),
    ('Setor da Saúde'),
    ('Utensílios de cozinha e utensílios de mesa'),
    ('Mobiliário doméstico/para escritório'),
    ('Equipamentos Esportivos'),
    ('Segurança / Vigilância'),
    ('Cuidados/alimentação para animais de estimação'),
    ('Fluidos/Combustíveis/Gases'),
    ('Ligações elétricas'),
    ('Segmento Transversal'),
    ('Vestuário'),
    ('Veículo'),
    ('Eletrodomésticos'),
    ('Materiais de Referência/Impressos/Textuais'),
    ('Música'),
    ('Acessórios Pessoais'),
    ('Informática'),
    ('Comunicações'),
    ('Artigos de Papelaria/ Equipamentos para Escritório'),
    ('Audiovisual / Fotografia'),
    ('Trabalho Artístico/Artesanato/Bordado'),
    ('Acampamento'),
    ('Produtos para Construção'),
    ('Ferramentas/Equipamentos-Manuais'),
    ('Encanamento/Aquecimento/Ventilação/Ar Condicionado'),
    ('Artigos de gramado/jardinagem'),
    ('Plantas de Horticultura'),
    ('Equipamentos para Oficina/Armazenagem de Ferramentas'),
    ('Ferramentas/Equipamentos-Elétricos'),
    ('Brinquedos/Jogos'),
    ('Lubrificantes'),
    ('Animais Vivos'),
    ('Segurança / Proteção - Bricolagem'),
    ('Recipientes para armazenamento/transporte'),
    ('Culturas'),
    ('Serviços / Máquinas de Venda'),
    ('Moeda / Certificados'),
    ('Matérias-primas (Não Alimentos)'),
    ('Produtos Post mortem'),
    ('Bombas/Sistemas de Fluidos Industriais'),
    ('OUTROS');
